name: EasyLumberjack
version: '1.0.0'
main: me.bitbox.EasyLumberjack
api-version: '1.16'
author: BITBOX
depend: [Vault]
commands:
  lumberjack:
    aliases:
      - lj
      - elj
      - easylumberjack
    description: "LumberJack Main command"